replicaCount: 2

image:
  repository: sansugupta/prima-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 80

env:
  AWS_REGION: "us-east-1"
  DYNAMODB_TABLE: "users"
  S3_BUCKET: "prima-tech-challenge"
  LOCALSTACK_URL: "http://localstack.default.svc.cluster.local:4566"


ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: prima-api.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: true
  name: "prima-api-sa"

